const enc=new TextEncoder(),dec=new TextDecoder();
function b64u(b){return btoa(String.fromCharCode(...new Uint8Array(b))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function fromb64u(s){s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hmac(secret,data){const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);return crypto.subtle.sign('HMAC',k,enc.encode(data))}
async function sign(secret,p){const x=b64u(enc.encode(JSON.stringify(p)));return x+'.'+b64u(await hmac(secret,x))}
async function verify(secret,t){try{const [p,s]=t.split('.');if(!p||!s)return null;const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('HMAC',k,fromb64u(s),enc.encode(p)))return null;const x=JSON.parse(dec.decode(fromb64u(p)));return x.exp>Date.now()/1000?x:null}catch{return null}}
function cors(env){return {'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN||'https://oemlive.github.io','Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}
function json(x,env,status=200,extra={}){return new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json;charset=utf-8',...cors(env),...extra}})}
function gh(env,path,init={}){const b=`https://api.github.com/repos/${env.REPO_OWNER||'oemlive'}/${env.REPO_NAME||'iptv'}`;return fetch(b+path,{...init,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${env.GITHUB_TOKEN}`,...(init.headers||{})}})}
async function auth(req,env){const m=(req.headers.get('Cookie')||'').match(/(?:^|; )sh_session=([^;]+)/);return m?verify(env.SESSION_SECRET||'',m[1]):null}
async function readFile(env,path){const r=await gh(env,`/contents/${path}?ref=main`);if(!r.ok)throw Error('GitHub file '+r.status);const x=await r.json();const bytes=Uint8Array.from(atob(x.content.replace(/\n/g,'')),c=>c.charCodeAt(0));return {text:dec.decode(bytes),sha:x.sha}}
async function writeFile(env,path,text,msg){let sha;try{sha=(await readFile(env,path)).sha}catch{}const body={message:msg,content:btoa(unescape(encodeURIComponent(text))),branch:'main'};if(sha)body.sha=sha;const r=await gh(env,`/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('GitHub write '+r.status);return r.json()}
async function fetchText(url){const x=new URL(url);if(!['http:','https:'].includes(x.protocol))throw Error('仅允许 HTTP/HTTPS');const r=await fetch(x.href,{redirect:'follow',headers:{'User-Agent':'Source-Hunter-PRO/11.1','Accept':'application/json,text/plain,text/*,*/*'}});const text=await r.text();return {text,type:r.headers.get('content-type')||'',url:r.url,status:r.status}}
function discoverSources(text,base){const o=JSON.parse(text);const out=[];for(const x of (o.lives||[])){if(!x||typeof x!=='object'||!x.url)continue;let u=String(x.url).trim();try{u=new URL(u,base).href}catch{}out.push({name:String(x.name||u),url:u,headers:x.headers||{},enabled:true,group:String(x.group||''),type:x.type??0,playerType:x.playerType??null,ua:x.ua||'',epg:x.epg||'',logo:x.logo||''})}const m=new Map();for(const x of out)if(!m.has(x.url))m.set(x.url,x);return [...m.values()]}
export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{headers:cors(env)});const u=new URL(req.url);
if(u.pathname==='/api/login'&&req.method==='POST'){const p=await req.json().catch(()=>({}));if(!env.ADMIN_PASSWORD||p.password!==env.ADMIN_PASSWORD)return json({message:'密码错误'},env,401);const now=Math.floor(Date.now()/1000),t=await sign(env.SESSION_SECRET,{iat:now,exp:now+2592000});return json({ok:true},env,200,{'Set-Cookie':`sh_session=${t}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=2592000`})}
if(u.pathname==='/api/logout'&&req.method==='POST')return json({ok:true},env,200,{'Set-Cookie':'sh_session=; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=0'});
if(u.pathname==='/api/session'&&req.method==='GET')return (await auth(req,env))?json({ok:true},env):json({message:'未授权'},env,401);
if(!(await auth(req,env)))return json({message:'未授权'},env,401);
try{
 if(u.pathname==='/api/discover'&&req.method==='GET'){const source=env.ROOT_CATALOG||'https://raw.giteeusercontent.com/oemive/iptv/raw/master/hw.json';const r=await fetchText(source);if(r.status<200||r.status>=300)throw Error('入口返回 HTTP '+r.status);const sources=discoverSources(r.text,r.url);await writeFile(env,'output/subscriptions.json',JSON.stringify({version:'11.1.0',source:source,count:sources.length,sources},null,2),'chore: refresh subscription catalog');return json({source,count:sources.length,sources},env)}
 if(u.pathname==='/api/channels'&&req.method==='GET'){const x=await readFile(env,'output/channels.json');const s=await readFile(env,'config/selection.json').catch(()=>({text:'{}'}));return json({channels:JSON.parse(x.text).channels||[],selection:JSON.parse(s.text)},env)}
 if(u.pathname==='/api/selection'&&req.method==='POST'){const p=await req.json();const clean={version:4,selected_subscriptions:Array.isArray(p.selected_subscriptions)?p.selected_subscriptions:[],selected_subscription_urls:Array.isArray(p.selected_subscription_urls)?p.selected_subscription_urls:[],selected_channels:p.selected_channels&&typeof p.selected_channels==='object'?p.selected_channels:{},excluded_channels:p.excluded_channels&&typeof p.excluded_channels==='object'?p.excluded_channels:{},default_selected:p.default_selected!==false,updated_at:new Date().toISOString()};await writeFile(env,'config/selection.json',JSON.stringify(clean,null,2),'web: update Source Hunter selection');return json({ok:true,selection:clean},env)}
 if(u.pathname==='/api/dispatch'&&req.method==='POST'){const p=await req.json().catch(()=>({}));const stage=['discover','channels','scan','export','auto'].includes(p.stage)?p.stage:'auto';const r=await gh(env,'/actions/workflows/daily-export.yml/dispatches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:'main',inputs:{stage}})});return json({ok:r.ok,status:r.status},env,r.ok?200:r.status)}
 if(u.pathname==='/api/fetch'&&req.method==='GET'){const target=u.searchParams.get('url')||'';const r=await fetchText(target);return json(r,env,r.status)}
 if(u.pathname==='/api/pull'&&req.method==='POST'){const r=await gh(env,'/actions/workflows/daily-export.yml/dispatches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:'main',inputs:{stage:'channels'}})});if(!r.ok)return json({message:'无法触发 Actions: '+r.status},env,r.status);return json({ok:true,queued:true},env)}
 if(u.pathname==='/api/run'&&req.method==='GET'){const r=await gh(env,'/actions/workflows/daily-export.yml/runs?per_page=5');if(!r.ok)return json({message:'读取 Actions 状态失败: '+r.status},env,r.status);const x=await r.json();const run=x.workflow_runs?.find(z=>z.name==='Source Hunter pipeline')||x.workflow_runs?.[0]||null;return json({run:run?{id:run.id,status:run.status,conclusion:run.conclusion,created_at:run.created_at,updated_at:run.updated_at,html_url:run.html_url}:null},env)}
 return json({message:'not found'},env,404)
}catch(e){return json({message:String(e.message||e)},env,500)}
}}
