let all=[],selected=new Set(JSON.parse(localStorage.getItem('iptv-selected')||'[]'));
let localSources=JSON.parse(localStorage.getItem('iptv-source-urls')||'[]');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cfg={owner:'oemlive',repo:'iptv',workflow:'crawl.yml',branch:'main',token:''};let activeRun=null;
const apiBase=()=>`https://api.github.com/repos/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}`;
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function headers(){return {'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(cfg.token?{'Authorization':`Bearer ${cfg.token}`}:{})}}
async function gh(path,opt={}){const r=await fetch(apiBase()+path,{...opt,headers:{...headers(),...(opt.headers||{})}});if(!r.ok){let t=await r.text(),msg=t;try{const j=JSON.parse(t);msg=j.message||t}catch{}throw new Error(`${r.status}: ${msg.slice(0,300)}`)}return r.status===204?null:r.json()}
function notify(t,err=false){$('#notice').textContent=t;$('#notice').className='notice '+(err?'error':'')}
function save(){localStorage.setItem('iptv-selected',JSON.stringify([...selected]))}
function saveSources(){localStorage.setItem('iptv-source-urls',JSON.stringify(localSources));renderSourceChips()}
function renderSourceChips(){const box=$('#localSources');box.innerHTML=localSources.map((u,i)=>`<span class="chip" title="${esc(u)}">${esc(u.length>72?u.slice(0,69)+'...':u)} <button data-src="${i}" title="删除">×</button></span>`).join('');$$('[data-src]').forEach(b=>b.onclick=()=>{localSources.splice(Number(b.dataset.src),1);saveSources()})}
async function load(){try{let r=await fetch('./data/index.json?'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(r.status);let j=await r.json();all=j.sources||[];$('#updated').textContent='数据更新：'+(j.updated_at?new Date(j.updated_at).toLocaleString():new Date().toLocaleString());render()}catch(e){$('#updated').textContent='暂无自动生成数据'}}
async function loadSummary(){try{let r=await fetch('./data/run-summary.json?'+Date.now(),{cache:'no-store'});if(!r.ok)return;let j=await r.json();$('#summary').textContent=`最近结果：发现 ${j.discovered??0} · 验证 ${j.validated??0} · 有效 ${j.valid??0}`}catch{}}
function filtered(){let q=$('#q').value.trim().toLowerCase(),gs=$$('[data-group]:checked').map(x=>x.dataset.group),ss=$$('[data-sub]:checked').map(x=>x.dataset.sub);return all.filter(x=>(!q||(x.name+' '+x.url+' '+x.origin).toLowerCase().includes(q))&&(!gs.length||gs.includes(x.group))&&(!ss.length||ss.includes(x.subgroup))&&(!$('#valid').classList.contains('on')||x.valid===true))}
function render(){let v=filtered();$('#total').textContent=all.length;$('#cctv').textContent=all.filter(x=>x.group==='央卫').length;$('#hktw').textContent=all.filter(x=>x.group==='港台').length;$('#other').textContent=all.filter(x=>x.group==='其他').length;$('#hd').textContent=all.filter(x=>(x.width||0)>=1920&&(x.height||0)>=1080).length;$('#rows').innerHTML=v.map(x=>`<tr><td><input class="pick" data-id="${esc(x.id)}" type="checkbox" ${selected.has(x.id)?'checked':''}></td><td><b>${esc(x.name)}</b></td><td>${esc(x.group)} / ${esc(x.subgroup)}</td><td>${x.width&&x.height?x.width+'×'+x.height:'-'}</td><td>${esc(x.audio_codec||'无')}</td><td>${x.latency_ms!=null?x.latency_ms+'ms':'-'}</td><td><strong>${x.score??'-'}</strong></td><td class="${x.valid?'ok':'bad'}">${esc(x.status)}</td><td>${esc(x.origin)}</td></tr>`).join('');$$('.pick').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.id):selected.delete(x.dataset.id);save()})}
function chosen(){return all.filter(x=>selected.has(x.id)&&x.valid===true)}
function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function runIsActive(r){return r&&['queued','in_progress'].includes(r.status)}
async function refreshRuns(){try{let j=await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}/runs?branch=${encodeURIComponent(cfg.branch)}&per_page=10`);let runs=j.workflow_runs||[];let r=runs.find(runIsActive)||runs[0];if(!r){activeRun=null;$('#runStatus').textContent='无任务';$('#runState').textContent='暂无任务';return}activeRun=r;$('#runName').textContent=`#${r.run_number} ${r.display_title||r.name||''}`;$('#runStatus').textContent=r.status+(r.conclusion?` / ${r.conclusion}`:'');$('#runTime').textContent=r.created_at?new Date(r.created_at).toLocaleString():'-';$('#runEnd').textContent=r.updated_at?new Date(r.updated_at).toLocaleString():'-';$('#runState').textContent=r.status==='in_progress'?'● 运行中':(r.status==='queued'?'◌ 排队中':(r.conclusion==='success'?'✓ 成功':r.conclusion||r.status));$('#runLink').href=r.html_url||'#';$('#cancelRun').disabled=!runIsActive(r);$('#rerunFailed').disabled=!r.conclusion||r.conclusion==='success';if(runIsActive(r)){try{let jobs=await gh(`/actions/runs/${r.id}/jobs?per_page=20`);let running=(jobs.jobs||[]).find(j=>j.status==='in_progress')||jobs.jobs?.find(j=>j.status==='queued');let step=running?.steps?.find(s=>s.status==='in_progress')?.name||running?.name;if(step)$('#runState').textContent+=' · '+step}catch{}}}catch(e){$('#runState').textContent='查询失败';notify('GitHub 查询失败：'+e.message,true)}}
async function loadSchedule(){try{let r=await fetch('./config/settings.json?'+Date.now(),{cache:'no-store'});let j=await r.json(),s=j.schedule||{};$('#scheduleEnabled').checked=s.enabled!==false;$('#timezone').value=s.timezone||'UTC';$('#times').value=(s.times||[]).join(',');$('#weekdays').value=(s.weekdays||[0,1,2,3,4,5,6]).join(',');$('#scheduleState').textContent=(s.enabled===false?'已关闭':'启用：'+(s.times||[]).join(', ')+' '+(s.timezone||'UTC'))}catch(e){$('#scheduleState').textContent='未读取到配置'}}
async function connect(){cfg.owner=$('#owner').value.trim()||'oemlive';cfg.repo=$('#repo').value.trim()||'iptv';cfg.workflow=$('#workflow').value.trim()||'crawl.yml';cfg.branch=$('#branch').value.trim()||'main';cfg.token=$('#token').value.trim();try{let repo=await gh('');await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}`);$('#conn').textContent=cfg.token?'GitHub 已连接':'公开模式 · 已验证';$('#conn').className='pill '+(cfg.token?'ok':'public');$('#modal').classList.add('hidden');notify(`已验证 ${repo.full_name||cfg.owner+'/'+cfg.repo}${cfg.token?' · PAT 已启用':''}`);await refreshRuns();await loadSchedule()}catch(e){cfg.token='';$('#conn').textContent='公开模式';$('#conn').className='pill public';notify('仓库/Workflow 检查失败：'+e.message,true)}}
function needToken(action){if(cfg.token)return true;$('#modal').classList.remove('hidden');notify(`${action}需要 GitHub PAT。普通查看、输入源地址和导出不需要。`,true);return false}
async function runNow(){if(!needToken('立即运行'))return;try{let j=await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}/runs?branch=${encodeURIComponent(cfg.branch)}&per_page=5`);let active=(j.workflow_runs||[]).find(runIsActive);if(active){notify(`已有任务运行中：#${active.run_number}，请等待完成`,true);return}let stability=Math.max(0,Math.min(60,Number($('#stability').value||0))),concurrency=Math.max(1,Math.min(64,Number($('#concurrency').value||12)));await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}/dispatches`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:cfg.branch,inputs:{stability_seconds:String(stability),concurrency:String(concurrency),force:'true'}})});notify('已提交任务，正在等待 GitHub 创建运行记录…');setTimeout(refreshRuns,1800)}catch(e){notify('启动失败：'+e.message,true)}}
async function rerunFailed(){if(!needToken('重跑失败'))return;if(!activeRun)return;try{await gh(`/actions/runs/${activeRun.id}/rerun-failed`,{method:'POST'});notify(`已提交 #${activeRun.run_number} 的失败步骤重跑`);setTimeout(refreshRuns,1500)}catch(e){notify('重跑失败：'+e.message,true)}}
async function cancel(){if(!needToken('取消任务'))return;if(!activeRun||!runIsActive(activeRun)){notify('当前没有可取消任务');return}try{await gh(`/actions/runs/${activeRun.id}/cancel`,{method:'POST'});notify(`已发送 #${activeRun.run_number} 取消请求`);setTimeout(refreshRuns,1200)}catch(e){notify('取消失败：'+e.message,true)}}
function parseWeekdays(){let a=$('#weekdays').value.split(',').map(x=>Number(x.trim())).filter(Number.isInteger);return [...new Set(a)].filter(x=>x>=0&&x<=6).sort((a,b)=>a-b)}
async function saveSchedule(){if(!needToken('保存调度'))return;let times=$('#times').value.split(',').map(x=>x.trim()).filter(Boolean);if(!times.length||times.some(x=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(x))){notify('时间格式必须为 HH:MM',true);return}if(times.some(x=>Number(x.slice(3))%5!==0)){notify('时间必须使用 00/05/10/15…55 分',true);return}let weekdays=parseWeekdays();if(!weekdays.length){notify('星期必须至少选择一个 0-6',true);return}try{let path='/contents/config/settings.json',f=await gh(path),raw=atob(f.content.replace(/\n/g,'')),bin=Uint8Array.from(raw,c=>c.charCodeAt(0)),j=JSON.parse(new TextDecoder().decode(bin));j.schedule={...(j.schedule||{}),enabled:$('#scheduleEnabled').checked,timezone:$('#timezone').value.trim()||'UTC',times:[...new Set(times)].sort(),weekdays,granularity_minutes:5};let bytes=new TextEncoder().encode(JSON.stringify(j,null,2)+'\n'),out='';bytes.forEach(b=>out+=String.fromCharCode(b));await gh(path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'chore: update scheduler config',content:btoa(out),sha:f.sha,branch:cfg.branch})});notify('调度配置已保存到 GitHub');$('#scheduleState').textContent=($('#scheduleEnabled').checked?'启用：':'已关闭：')+times.join(', ')+' '+($('#timezone').value||'UTC')}catch(e){notify('保存调度失败：'+e.message,true)}}
async function loadExternalSource(){let u=$('#sourceUrl').value.trim();if(!u){notify('先输入一个 M3U / TXT / JSON 地址',true);$('#sourceUrl').focus();return}try{new URL(u)}catch{$('#sourceStatus').textContent='地址格式不正确';notify('请输入完整的 http(s) 地址',true);return}if(!localSources.includes(u)){localSources.unshift(u);localSources=localSources.slice(0,20);saveSources()}$('#sourceStatus').textContent='正在读取…';try{let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);let text=await r.text(),count=(text.match(/^#EXTINF/igm)||[]).length;if(!count){let lines=text.split(/\r?\n/).filter(x=>x.trim()&&!x.trim().startsWith('#'));count=Math.floor(lines.length/2)}$('#sourceStatus').textContent=`读取成功：约 ${count} 个条目`;notify(`源已读取：${u}。当前页面的数据表仍显示仓库自动生成结果；外部源地址已保存在本机列表。`)}catch(e){$('#sourceStatus').textContent='浏览器读取失败';notify('读取失败：'+e.message+'。常见原因是目标站点未开启 CORS；可点击“在新窗口打开”确认地址，或交给 GitHub 爬虫验证。',true)}}
function openSource(){let u=$('#sourceUrl').value.trim();if(u)window.open(u,'_blank','noopener')}
$('#settingsBtn').onclick=()=>$('#modal').classList.remove('hidden');$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#helpBtn').onclick=()=>$('#helpModal').classList.remove('hidden');$('#closeHelp').onclick=()=>$('#helpModal').classList.add('hidden');$('#connect').onclick=connect;$('#disconnect').onclick=()=>{cfg.token='';$('#token').value='';$('#conn').textContent='公开模式';$('#conn').className='pill public';notify('PAT 已清除；页面仍可公开查看和使用源地址功能')};$('#runNow').onclick=runNow;$('#cancelRun').onclick=cancel;$('#rerunFailed').onclick=rerunFailed;$('#refresh').onclick=()=>{refreshRuns();load();loadSummary()};$('#saveSchedule').onclick=saveSchedule;$('#loadSource').onclick=loadExternalSource;$('#openSource').onclick=openSource;$('#pasteSource').onclick=async()=>{try{$('#sourceUrl').value=await navigator.clipboard.readText();notify('已从剪贴板读取地址')}catch{notify('浏览器不允许直接读取剪贴板，请手动粘贴',true)}};$('#clearSources').onclick=()=>{localSources=[];saveSources();$('#sourceStatus').textContent='已清空本地源'};$$('[data-group],[data-sub]').forEach(x=>x.onchange=render);$('#q').oninput=render;$('#valid').onclick=()=>{$('#valid').classList.toggle('on');render()};$('#all').onclick=()=>{filtered().forEach(x=>selected.add(x.id));save();render()};$('#none').onclick=()=>{filtered().forEach(x=>selected.delete(x.id));save();render()};$('#head').onchange=e=>{filtered().forEach(x=>e.target.checked?selected.add(x.id):selected.delete(x.id));save();render()};$('#exportTxt').onclick=()=>download('selected.txt',chosen().map(x=>x.name+','+x.url).join('\n')+'\n');$('#exportM3u').onclick=()=>download('selected.m3u','#EXTM3U\n'+chosen().map(x=>`#EXTINF:-1 group-title="${x.group}/${x.subgroup}",${x.name}\n${x.url}`).join('\n')+'\n');$('#exportConfig').onclick=()=>download('selected-sources.json',JSON.stringify(chosen(),null,2));renderSourceChips();load();loadSummary();loadSchedule();refreshRuns();setInterval(refreshRuns,15000);
