let all=[], selected=new Set(JSON.parse(localStorage.getItem('iptv-selected')||'[]'));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg={owner:'oemlive',repo:'iptv',workflow:'crawl.yml',branch:'main',token:''};
const apiBase=()=>`https://api.github.com/repos/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}`;
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function headers(){return {'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(cfg.token?{'Authorization':`Bearer ${cfg.token}`}:{})}}
async function gh(path,opt={}){let r=await fetch(apiBase()+path,{...opt,headers:{...headers(),...(opt.headers||{})}});if(!r.ok){let t=await r.text();throw new Error(`${r.status}: ${t.slice(0,300)}`)}return r.status===204?null:r.json()}
function notify(t,err=false){$('#notice').textContent=t;$('#notice').className='notice '+(err?'error':'')}
function save(){localStorage.setItem('iptv-selected',JSON.stringify([...selected]))}
async function load(){try{let r=await fetch('./data/index.json?'+Date.now());let j=await r.json();all=j.sources||[];$('#updated').textContent='数据更新：'+new Date().toLocaleString();render()}catch(e){$('#updated').textContent='暂无自动生成数据'}}
function filtered(){let q=$('#q').value.trim().toLowerCase(),gs=$$('[data-group]:checked').map(x=>x.dataset.group),ss=$$('[data-sub]:checked').map(x=>x.dataset.sub);return all.filter(x=>(!q||(x.name+' '+x.url+' '+x.origin).toLowerCase().includes(q))&&(!gs.length||gs.includes(x.group))&&(!ss.length||ss.includes(x.subgroup))&&(!$('#valid').classList.contains('on')||x.valid===true))}
function render(){let v=filtered();$('#total').textContent=all.length;$('#cctv').textContent=all.filter(x=>x.group==='央卫').length;$('#hktw').textContent=all.filter(x=>x.group==='港台').length;$('#other').textContent=all.filter(x=>x.group==='其他').length;$('#hd').textContent=all.filter(x=>(x.width||0)>=1920&&(x.height||0)>=1080).length;$('#rows').innerHTML=v.map(x=>`<tr><td><input class="pick" data-id="${esc(x.id)}" type="checkbox" ${selected.has(x.id)?'checked':''}></td><td><b>${esc(x.name)}</b></td><td>${esc(x.group)} / ${esc(x.subgroup)}</td><td>${x.width&&x.height?x.width+'×'+x.height:'-'}</td><td>${esc(x.audio_codec||'无')}</td><td>${x.latency_ms?x.latency_ms+'ms':'-'}</td><td><strong>${x.score??'-'}</strong></td><td class="${x.valid?'ok':'bad'}">${esc(x.status)}</td><td>${esc(x.origin)}</td></tr>`).join('');$$('.pick').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.id):selected.delete(x.dataset.id);save()})}
function chosen(){return all.filter(x=>selected.has(x.id)&&x.valid===true)}
function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function refreshRuns(){if(!cfg.token)return;try{let j=await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}/runs?per_page=10`);let runs=j.workflow_runs||[],r=runs[0];if(!r){$('#runStatus').textContent='无任务';return}$('#runName').textContent=`#${r.run_number} ${r.name||''}`;$('#runStatus').textContent=r.status+(r.conclusion?` / ${r.conclusion}`:'');$('#runTime').textContent=r.created_at?new Date(r.created_at).toLocaleString():'-';$('#runEnd').textContent=r.updated_at?new Date(r.updated_at).toLocaleString():'-';$('#runState').textContent=r.status==='in_progress'?'● 运行中':(r.conclusion==='success'?'✓ 成功':r.conclusion||r.status);$('#runLink').href=r.html_url||'#';$('#cancelRun').disabled=r.status!=='queued'&&r.status!=='in_progress';}catch(e){$('#runState').textContent='查询失败';notify('GitHub 查询失败：'+e.message,true)}}
async function loadSchedule(){try{let r=await fetch('./config/settings.json?'+Date.now());let j=await r.json(),s=j.schedule||{};$('#scheduleEnabled').checked=s.enabled!==false;$('#timezone').value=s.timezone||'UTC';$('#times').value=(s.times||[]).join(',');$('#scheduleState').textContent=(s.enabled===false?'已关闭':'启用：'+(s.times||[]).join(', ')+' '+(s.timezone||'UTC'))}catch(e){}}
async function connect(){cfg.owner=$('#owner').value.trim()||'oemlive';cfg.repo=$('#repo').value.trim()||'iptv';cfg.workflow=$('#workflow').value.trim()||'crawl.yml';cfg.branch=$('#branch').value.trim()||'main';cfg.token=$('#token').value.trim();if(!cfg.token){notify('请输入 GitHub PAT',true);return}try{let j=await gh('');$('#conn').textContent='GitHub 已连接';$('#conn').classList.add('ok');$('#modal').classList.add('hidden');notify(`已连接 ${j.full_name||cfg.owner+'/'+cfg.repo}`);await refreshRuns();await loadSchedule()}catch(e){cfg.token='';notify('连接失败：'+e.message,true)}}
async function runNow(){if(!cfg.token){$('#modal').classList.remove('hidden');notify('请先连接 GitHub',true);return}try{await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}/dispatches`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:cfg.branch,inputs:{stability_seconds:String($('#stability').value||0),concurrency:String($('#concurrency').value||12),force:'true'}})});notify('已提交 workflow_dispatch，正在等待 GitHub 创建任务…');setTimeout(refreshRuns,1800)}catch(e){notify('启动失败：'+e.message,true)}}
async function rerunFailed(){if(!cfg.token)return;try{let j=await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}/runs?per_page=1`),r=j.workflow_runs?.[0];if(!r){notify('没有可重跑任务');return}await gh(`/actions/runs/${r.id}/rerun-failed`,{method:'POST'});notify('已提交失败步骤重跑');setTimeout(refreshRuns,1500)}catch(e){notify('重跑失败：'+e.message,true)}}
async function cancel(){if(!cfg.token)return;try{let j=await gh(`/actions/workflows/${encodeURIComponent(cfg.workflow)}/runs?per_page=1`);let r=j.workflow_runs?.[0];if(!r||!['queued','in_progress'].includes(r.status)){notify('当前没有可取消任务');return}await gh(`/actions/runs/${r.id}/cancel`,{method:'POST'});notify('已发送取消请求');setTimeout(refreshRuns,1000)}catch(e){notify('取消失败：'+e.message,true)}}
async function saveSchedule(){if(!cfg.token){$('#modal').classList.remove('hidden');notify('保存调度需要 GitHub 连接',true);return}let times=$('#times').value.split(',').map(x=>x.trim()).filter(Boolean);if(times.some(x=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(x))){notify('时间格式必须为 HH:MM',true);return}try{let path='/contents/config/settings.json',f=await gh(path);let raw=atob(f.content.replace(/\n/g,''));let j=JSON.parse(new TextDecoder().decode(Uint8Array.from(raw,c=>c.charCodeAt(0))));j.schedule={...(j.schedule||{}),enabled:$('#scheduleEnabled').checked,timezone:$('#timezone').value.trim()||'UTC',times,weekdays:[0,1,2,3,4,5,6]};let bytes=new TextEncoder().encode(JSON.stringify(j,null,2)+'\n'),bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));await gh(path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'chore: update scheduler config',content:btoa(bin),sha:f.sha,branch:cfg.branch})});notify('调度配置已写入 GitHub；下次 15 分钟调度周期会按新配置执行');$('#scheduleState').textContent=($('#scheduleEnabled').checked?'启用：':'已关闭：')+times.join(', ')+' '+($('#timezone').value||'UTC')}catch(e){notify('保存调度失败：'+e.message,true)}}
$('#settingsBtn').onclick=()=>$('#modal').classList.remove('hidden');$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#connect').onclick=connect;$('#disconnect').onclick=()=>{cfg.token='';$('#conn').textContent='未连接';notify('已断开 GitHub');};$('#runNow').onclick=runNow;$('#cancelRun').onclick=cancel;$('#rerunFailed').onclick=rerunFailed;$('#refresh').onclick=()=>{refreshRuns();load()};$('#saveSchedule').onclick=saveSchedule;$$('[data-group],[data-sub]').forEach(x=>x.onchange=render);$('#q').oninput=render;$('#valid').onclick=()=>{$('#valid').classList.toggle('on');render()};$('#all').onclick=()=>{filtered().forEach(x=>selected.add(x.id));save();render()};$('#none').onclick=()=>{filtered().forEach(x=>selected.delete(x.id));save();render()};$('#head').onchange=e=>{filtered().forEach(x=>e.target.checked?selected.add(x.id):selected.delete(x.id));save();render()};$('#exportTxt').onclick=()=>download('selected.txt',chosen().map(x=>x.name+','+x.url).join('\n')+'\n');$('#exportM3u').onclick=()=>download('selected.m3u','#EXTM3U\n'+chosen().map(x=>`#EXTINF:-1 group-title="${x.group}/${x.subgroup}",${x.name}\n${x.url}`).join('\n')+'\n');$('#exportConfig').onclick=()=>download('selected-sources.json',JSON.stringify(chosen(),null,2));load();loadSchedule();setInterval(refreshRuns,15000);
